version: '3.8'

services:
  # Spring Boot Application
  app-container:
    container_name: app-container 
    image: zagalovontogo/gestiondestock:latest  # Update with your actual image details
    ports:
      - "8882:8881"
    env_file:
      - ./gestiondestock-env-file.env  # Path to your combined environment file
    depends_on:
      - db-container

  # MySQL Database
  db-container:
    container_name: db-container
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./gestiondestock-env-file.env  # Path to your combined environment file
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: {}

