spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ejb:
          interceptor: org.mambey.gestiondestock.interceptor.Interceptor

gimuemoa:
  openapi:
    prod-url: https://gimuemoa-api.com


server:
  port: 8881

# App Security Properties
edem:
  app:
    jwtHeaderName: Authorization
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

#uploadDir: /Users/admin/gestionStockUploads
#uploadDir: src${file.separator}main${file.separator}resources${file.separator}uploads${file.separator}
uploadDir: ${user.home}${file.separator}gestiondestock${file.separator}uploads${file.separator}

defaultImageName: default.jpg

defaultUserPassword: Zagzagzag

logging:
  level:
    org:
      springframework: INFO
  # file:
  #   name: /Users/admin/gestiondestock.log


  
