spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ejb:
          interceptor: org.mambey.gestiondestock.interceptor.Interceptor

gimuemoa:
  openapi:
    dev-url: http://localhost:8881


server:
  port: 8881

flickr:
  apiKey: 21afae5646e01df8b2cba088bef1f0d9
  apiSecret: 30d27f0d5c5958ba
  appKey: 72157720884054158-79f70eebab71910d
  appSecret: 53cfc158c56ce6a1

# App Security Properties
edem:
  app:
    jwtHeaderName: Authorization
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

defaultUserPassword: Zagzagzag

#uploadDir: /Users/admin/gestionStockUploads
#uploadDir: src${file.separator}main${file.separator}resources${file.separator}uploads${file.separator}
uploadDir: ${user.home}${file.separator}gestiondestock${file.separator}uploads${file.separator}

defaultImageName: default.jpg

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      springframework: DEBUG
  file:
    #name: /Users/admin/gestiondestock.log
    name: ${user.home}${file.separator}gestiondestock${file.separator}logs${file.separator}gestiondestock.log


  
